import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";

const robotoSlab = Roboto_Slab({
	variable: "--font-roboto-slab",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Nick Costello",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${robotoSlab.className} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
